### ISSUE TITLE
Private init

### ISSUE THREAD

**Issue by angeldev** [hpique/SwiftSingleton#13]
Hi, first of all thanks you very much for this repo, I found it very useful. Just, I wonder if class constant approach could be incomplete. Isn't necessary a private init? with this current implementation you could create several references of the same class, with a private init you only could create one instance (the static property). 

Thanks.

**Comment by gabrielmadruga** [comment]
You are correct, in fact the .swift example is already updated. I made a pull request for this: https://github.com/hpique/SwiftSingleton/pull/14
