### ISSUE TITLE
Best approach changes with Swift 1.2!?

### ISSUE THREAD

**Issue by Dschee** [hpique/SwiftSingleton#5]
I just read through the Release notes of XCode 6.3b1 which states the following:

> “static” methods and properties are now allowed in classes (as an alias for “class final”). You are now allowed to declare static stored properties in classes, which have global storage and are lazily initialized on first access (like global variables).

If I understand this correctly, then this should change both the syntax of A and the overall recommendation to A. What do you think?

I can't try it out myself right now but will have a look at it later if no one else does.

**Comment by hpique** [comment]
Go for it!

**Comment by Dschee** [comment]
I have just had a look into it and created a pull request with my solution and changes. Please have a look here: https://github.com/hpique/SwiftSingleton/pull/6.

**Comment by hpique** [comment]
Thanks @Dschee! Merged.
