### ISSUE TITLE
Singleton with parameters?

### ISSUE THREAD

**Issue by burczyk** [hpique/SwiftSingleton#9]
Great article!
I would like to ask you: do you have some clever solution for a Singleton to which we need to pass parameters? Let's say URL and APIKey? Solution with class constant doesn't work due to initialization order. Which approach would you suggest?

**Comment by lobinhojr** [comment]
I have the same question. What do you think about this? Singleton with parameters.

**Comment by Dschee** [comment]
What's the matter with using simple object properties?

**Comment by Dschee** [comment]
Here is an example of how this might look like using Approach A in this repository:

``` Swift
//: A simple parameterized Singleton example

import UIKit

// The Singleton class with parameters
class SingletonA {
    
    // MARK: - Class Stored Properties
    
    static let sharedInstance = SingletonA()
    
    
    // MARK: - Object Stored Properties
    
    private let baseUrl = "http://https://github.com/hpique/SwiftSingleton"
    private let apiKey = {
        // TODO: Get your API-Key from a secure place (like the Keychain)
        return "your retrieved API-Key"
    }()
    
    
    // MARK: - Initialization Methods
    
    init() {
        println("AAA");
        
        // Note: Alternatively you could set the baseUrl and apiKey values here
    }
    
    
    // MARK: - Object Methods
    
    // TODO: Your methods go here ...
}


// Usage:
SingletonA.sharedInstance


//: Please note that you could make the Object Stored Properties non-private
//: in order to be able to use them in other classes.
```

**Comment by Dschee** [comment]
If this doesn't answer your question you might be better with using a different pattern than a Singleton. See this [great answer](http://stackoverflow.com/a/1300730/3451975) on StackOverflow as a first read for that.

**Comment by burczyk** [comment]
Well, they have to be compile-time constants. I was thinking if there is a way to create singleton using syntax `SingletonA('abc')` where you provide initialization data only once.

**Comment by Dschee** [comment]
In that case, just use the [Factory pattern](http://www.oodesign.com/factory-pattern.html) instead – Singletons are not made for this. You can still create a class that holds your factory object(s) as a class property though so you can use your factory object everywhere in your code, much like a Singleton.

**Comment by burczyk** [comment]
Thanks for explanation, it is really useful.

**Comment by Dschee** [comment]
Glad I could help. I suggest we close this issue then as this is not really an issue with this repository (which is intended to be an implementation of the Singleton pattern only).

**Comment by burczyk** [comment]
Sure, simply didn't have idea how to chat otherwise :)
